FROM golang

RUN go get github.com/Masterminds/glide

WORKDIR /go/src/github.com/tienducitt/go-restful/src
COPY glide.* ./
COPY vendor .

RUN glide install 

COPY . .

RUN go build -o go-restful

EXPOSE 8080
CMD ./go-restful start